services:

  postgres:
    image: postgres:16-alpine
    container_name: predmaint_postgres
    environment:
      POSTGRES_DB: predictive_maintenance_db
      POSTGRES_USER: predmaint
      POSTGRES_PASSWORD: predmaint_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: